## Numpy Random

In [ ]:
from numpy import random

x = random.randint(100) # this generate random integer from 0 - 100
print(x)

rand_Float = random.rand()
print(rand_Float)

39
0.6855897559460282


### Generate random array 

In [13]:
randomarray = random.randint(100, size=(6))
print(randomarray)

[34 15 65 34 43 66]


In [15]:
# generate a 2D random array 
random_2d = random.randint(100,size=(2,4))
print(random_2d)  # size=(2row, 4column)

[[98 50 32  6]
 [53 34 97 31]]


### Generate random Number from array 

In [8]:
import numpy as np

array = np.array([1,2,3,4,5])
random_from_array = random.choice(array)
print(random_from_array)


2


In [ ]:
random_2d_choice = random.choice([4,5,6,7], size=(3,5)) # yo [4,5,6,7] array bata 3ta row ani 4 ta column vako matrix banaidinxa 

print(random_2d_choice)

[[4 7 6 4 6]
 [4 6 7 5 7]
 [4 5 7 7 5]]


## Data Distribution 

In [17]:
randomdatadistribution = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0], size=(100))
print(randomdatadistribution)

randomdata_2d = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0], size=(3,4))

print(randomdata_2d)

[7 7 7 7 7 7 7 7 7 7 7 5 5 7 7 7 5 7 5 7 5 7 7 7 7 3 3 7 5 3 5 5 7 7 5 7 7
 7 3 5 7 7 5 5 7 7 3 5 7 3 7 7 5 5 7 7 5 7 7 5 7 7 7 7 5 7 5 7 5 5 7 5 5 5
 5 5 7 7 7 7 3 7 5 5 5 5 5 7 7 7 7 7 5 3 7 5 7 7 7 5]
[[3 7 7 5]
 [7 5 7 7]
 [7 5 7 7]]


### Random permutation of elements 

In [ ]:
arr = np.array([1,2,3,4,5])
random.shuffle(arr) # shuffle means changing arrangements of elements 
print(arr)

[2 3 1 5 4]


In [29]:
# generating the permutation : 
arr1 = np.array([1,2,3,4,5])

print(random.permutation(arr1)) # permutation method returns a rearrange and leaves the original array unchanged 

arr2 = np.arange(0,10,2)
print(arr2)

[3 5 2 4 1]
[0 2 4 6 8]
