In [2]:
import numpy as np 

### creating array from list 

In [8]:
array1D = np.array([1,2,3])
print("1D array: ", array1D)
print("shape of 1D array: ",array1D.shape)
array2D = np.array([[1,2,3],[4,5,6]])
print("2D array: ",array2D)
print("shape of 2D array: ",array2D.shape)

1D array:  [1 2 3]
shape of 1D array:  (3,)
2D array:  [[1 2 3]
 [4 5 6]]
shape of 2D array:  (2, 3)


### list vs numpy array

In [13]:
py_list = [1,2,3,4]
print("Python list nultiplication: ", py_list * 2)

np_array = np.array([1,2,3,4]) # element wise multiplication hunxa yesma chai 
print("Numpy array multiplication: ", np_array * 2)

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time: ",time.time()- start)

start = time.time()
np_array = np.arange(1000000) *2
print("Numpy operation time: ",time.time()- start)


Python list nultiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication:  [2 4 6 8]
List operation time:  0.08420634269714355
Numpy operation time:  0.0039899349212646484


### Array fundamental

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(a[0]) # indexing tesari nai hunxa 
a[0] = 9 #numpy array is mutable 
print(a)
b = a[:3] #slice notation can be used for indexing ra yeslai view pani vaninxa
print(b)
b[1]= 45 # the original array can be mutatetd using the view 
print(a)

[1 2 3 4 5]
1
[9 2 3 4 5]
[9 2 3]
[ 9 45  3  4  5]


### creating array from scratch 

In [29]:
zeros = np.zeros((3,4)) # this will create a 0's array
print("Zeros array: \n", zeros)

ones = np.ones((2,3)) # this will create a ones array 
print("\nOnes array: \n", ones)

full = np.full((2,2),7) # Return a new array of given shape and type filled with fill_value
print("\nFull array: \n", full)

random = np.random.random((2,3))
# Return a new array of given shape and type filled with random samples from a uniform distribution over 
print("\n random fill : \n",random)

sequence = np.arange(0, 10, 2)
print("\n Sequence array: \n",sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

Full array: 
 [[7 7]
 [7 7]]

 random fill : 
 [[0.58187235 0.60629996 0.71887137]
 [0.68706428 0.20148768 0.57327302]]

 Sequence array: 
 [0 2 4 6 8]


### vector, Matrix and Tensor

In [ ]:
vector = np.array([1,2,3,4]) # 1D = vector
print("Vector: \n", vector)

matrix = np.array([[1,2,3,4],[6,7,8,9]]) # 2D = matrix
print("Matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],  #n-d = tensor 
                    [[6,7],[9,8]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3 4]
Matrix: 
 [[1 2 3 4]
 [6 7 8 9]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[6 7]
  [9 8]]]


### Array Properties

In [39]:
arr = np.array([[1,2,3],   #similar datatypes lai chai 
                [5,6,7]])  
print("Shape: ",arr.shape) # shape of matrix like rows column
print("Dimension: ",arr.ndim) # give the dimension of matrix
print("Size: ",arr.size) # gives the total element in array
print("DType: ",arr.dtype) # gives the datatype of an array 

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


### Array Reshaping

In [45]:
arr = np.arange(12)
print("Original Array : ",arr)

# return the copy with reshape
reshape = arr.reshape((3,4)) #can reshape in out own way but it should be valid
print("\n Reshaped Array : ",reshape)

flattened = reshape.flatten()
print("\n Flatterned array. ",flattened)

# ravel (returns the view, insted of copy) original array ko view lai matra return gariraxa 
raveled = reshape.ravel()
print("\n Raveled array : ",raveled)

# Transpose matrix 
transpose = reshape.T
print("\n Transpose array : ",transpose)


Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatterned array.  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
