## Numpy Array operations 

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing",arr[0:5])
print("With step ", arr[1:8:2])
print("Negative Indexing: ", arr[-2])

Basic slicing [1 2 3 4 5]
With step  [2 4 6 8]
Negative Indexing:  8


### Indexing slicing in 2D array 

In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Elements: ", arr_2d[1,2])
print("Entire row: ",arr_2d[0])
print("Entire column: ",arr_2d[:,1])


Specific Elements:  6
Entire row:  [1 2 3]
Entire column:  [2 5 8]


## Slicing 

In [5]:
unsorted = np.array([4,1,6,2,12,8,6,11,13])
print("Sorted Array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column: \n",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by row: \n",np.sort(arr_2d_unsorted,axis=1))

Sorted Array:  [ 1  2  4  6  6  8 11 12 13]
Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row: 
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [6]:
numbers = np.arange(1,11)
print(numbers)
even_numbers = numbers[numbers % 2 == 0] # numpy allows to write the expression in array data format 
print(even_numbers)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


## Filter with mask

In [7]:
mask = numbers > 5
print(" Numbers greater than 5 is ", numbers[mask]) # this allows to evaluate the value with each value of the mask 


 Numbers greater than 5 is  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices]) 

where_result = np.where(numbers> 5) # where ma cha powerful expression halera aafnai hisab ko tyo value lina pani painxa .. np.where() le pani array nai create garxa tara specific condition ma perform garna milyo 
print(where_result)
print("Np where ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np where  [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers> 5,numbers * 3, numbers) # where() ma chai .. np.where(condition, true huda yo execute garxa, false ma yo execute garxa)
print(condition_array)

more_condition = np.where(numbers> 5, "True", "False")

print(more_condition)

[ 1  2  3  4  5 18 21 24 27 30]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## Adding and removing data

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

# combined = arr1 + arr2  # + operation le sum garxa array ma chai naki jodney 
# print("Combined Array: ", combined)

combined = np.concatenate((arr1, arr2))
print("Combined Array: ", combined)

Combined Array:  [1 2 3 4 5 1 7 8]


## array compatibility 

In [ ]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([1,2,3])

print("Compatibility Shapes: ",a.shape == b.shape)

Compatibility Shapes:  False


In [15]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6]) 
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


## Delete

In [18]:
arra = np.array([1,2,3,4,5])
deleted_array = np.delete(arra, 3)
print("Deleted Array: ",deleted_array)

Deleted Array:  [1 2 3 5]
