### Numpy practice 

In [1]:
import numpy as np

In [3]:
array1 = np.array([1,2,3,4])
print(array1)
print(array1.shape)

# This is two dimension array called matrix 
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)
print("Shape of array: ",array2.shape)
print("size of an array: ",array2.size)
print("datatype of array: ",array2.dtype)
print("dimesion: ",array2.ndim)
print(len(array2.shape) == array2.ndim)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
Shape of array:  (2, 4)
size of an array:  8
datatype of array:  int64
dimesion:  2
True


#### creating the basic array 

In [4]:
zeros = np.zeros((3,2))
print(zeros)

ones = np.ones((3,3))
print(ones)

empty = np.empty((2,2))
print(empty)

arange = np.arange(2,11,2)
print(arange)

#create an array with values that are spaced linearly in specified interva 
linespace = np.linspace(0,10, num=5)
print(linespace)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.00000000e+000 9.38366282e-312]
 [9.38366283e-312 9.38366283e-312]]
[ 2  4  6  8 10]
[ 0.   2.5  5.   7.5 10. ]


### Adding, removing, and sorting elements 

In [5]:
arr = np.array([1,4,12,2,0,9,11,7,5,13])
sorted1D = np.sort(arr)
print(arr)
print(sorted1D)

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

concatinate = np.concatenate((a,b))
print(concatinate)

x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[8,9,10,11]])
concat2D = np.concatenate((x,y), axis=0)
print(concat2D)

new_array = np.arange(0,11,2)
print(new_array)

print("\n")
reshape = np.reshape(new_array, shape=(2,3), order='C')
print(reshape)

flattern = reshape.flatten()
print(flattern)

# transpose the matrix into row into column and column into row
transpose = reshape.T
print(transpose)


[ 1  4 12  2  0  9 11  7  5 13]
[ 0  1  2  4  5  7  9 11 12 13]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10]


[[ 0  2  4]
 [ 6  8 10]]
[ 0  2  4  6  8 10]
[[ 0  6]
 [ 2  8]
 [ 4 10]]


In [7]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
for x in array_2d:
    print(x)

for x in array_2d:
    for y in x:
        print(y)
        

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


### Iterating 3-D arrays 

In [9]:
array_3d = np.array([[[1,2,3,4],[4,5,6,7]],[[7,8,9,10],[10,11,12,13]]])
for x in array_3d:
    print(x)

[[1 2 3 4]
 [4 5 6 7]]
[[ 7  8  9 10]
 [10 11 12 13]]


In [ ]:
another_3d_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(another_3d_array):# for loop chai normal ko lagi better hunxa but as dimension badhdai janxa it gets complex so use the np.nditer() function instead
    print(x)

1
2
3
4
5
6
7
8


### Iterating Array with Different Data types


In [11]:
array = np.array([1,2,3,4])
for x in np.nditer(array,flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]): # [:, ::2] : all rows, :: starting column with default and 2 is skip part 
  print(x)

1
3
5
7


### Enumerated Iteration Using ndenumerate()

In [13]:
arra = np.array([1,2,3,4])
for idx, x in np.ndenumerate(arra):
    print(f"index: {idx}, value: {x}")

index: (0,), value: 1
index: (1,), value: 2
index: (2,), value: 3
index: (3,), value: 4


In [14]:
ar = np.array([[1,2,3],[4,5,6]])
for idx, x in np.ndenumerate(ar):
    print(f"index: {idx}, value: {x}")

index: (0, 0), value: 1
index: (0, 1), value: 2
index: (0, 2), value: 3
index: (1, 0), value: 4
index: (1, 1), value: 5
index: (1, 2), value: 6


### Joining in NumPy Array

In [15]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
final = np.concatenate((arr1,arr2))
print(final)

[1 2 3 4 5 6 7 8]


### Joining 2D array 




In [ ]:
arr_1 = np.array([[1,2],[3,4]])

arr_2 = np.array([[5,6],[7,8]])

final_2d = np.concatenate((arr_1, arr_2), axis=0) # 0 => column , 1 => row wise

print(final_2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Joining array using stack

In [25]:
arra_1= np.array([1,2,3,4])
arra_2 = np.array([4,5,7,8])

final_stack_array = np.stack((arra_1,arra_2), axis=0)

print(final_stack_array)

hstack = np.hstack((arra_1,arra_2))
print("hstack: ", hstack)

vstack = np.vstack((arra_1,arra_2))

print("vstack: ", vstack)


[[1 2 3 4]
 [4 5 7 8]]
hstack:  [1 2 3 4 4 5 7 8]
vstack:  [[1 2 3 4]
 [4 5 7 8]]


In [13]:
arr__1 = np.array([1,2,3,4,5,6])

newarray = np.array_split(arr__1, 3)

print(newarray)

splitarray = np.split(arr__1, 3)
print("splitarray: ", splitarray) ## split huna ko lagi chai exactly array ko group hunu parney raixa 

print(newarray[0])
print(newarray[1])
print(newarray[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
splitarray:  [array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [26]:
split_2d_array = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
split_2d_result = np.array_split(split_2d_array,3, axis=0)
print("split_2d_result:\n ",split_2d_result)

hsplit = np.hsplit(split_2d_array,2)
print("hsplit:\n ",hsplit)


split_2d_result:
  [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
hsplit:
  [array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Searching Array

In [30]:
arr_final = np.array([1,2,3,4,5,6,7,8,8,4,4,2])
x = np.where(arr_final == 8) # returns indices of 8

print(x)

even = np.where(arr_final%2 == 0) # index nai find gariraxa yesle where the value of array is even
print("Index of an even array is : ",even)

(array([7, 8]),)
Index of an even array is :  (array([ 1,  3,  5,  7,  8,  9, 10, 11]),)


In [35]:
# search sorted : 
sortedarray = np.array([6,7,8,9])
sort = np.searchsorted(sortedarray, 8) # sorted array ma 8 ko index chai kaha parxa vanera khojxa yesle chai 

print(sort)

sortfromright = np.searchsorted(sortedarray, 7, side='right')
print(sortfromright)

# search multiple values : 
sortedwithgap = np.array([1,3,5,7])
multiplevalues = np.searchsorted(sortedwithgap, [2,4,6])
print(multiplevalues)

2
2
[1 2 3]


### Numpy Sorting array 

In [41]:
arraytosort = np.array([3,1,9,6,8])
sortedarrayvalue = np.sort(arraytosort, axis=0) # since it is vector the row sorted with axis=1 is not available 

print(sortedarrayvalue)

stringarray = np.array(['banana','cherry','apple'])
sortedstringarray = np.sort(stringarray,)
print(sortedstringarray)

#sorting 2d array 
unsorted2d = np.array([[3,2,4],[5,0,1]])
print("Sorted 2d array: ", np.sort(unsorted2d, axis=0)) # column wise sorting 
print("Sorted 2d array: ", np.sort(unsorted2d, axis=1)) # row wise sorting 

[1 3 6 8 9]
['apple' 'banana' 'cherry']
Sorted 2d array:  [[3 0 1]
 [5 2 4]]
Sorted 2d array:  [[2 3 4]
 [0 1 5]]


In [44]:
arr = np.array([41,42,43,44,45,46,47])

#create an empty list 
filter_arr = []

for element in arr:
    if element > 43:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newfiltered = arr[filter_arr]
print("New filtered array: ", newfiltered)
print(filter_arr)


# creating filter diretly from array 

filter_arr_direct = arr> 42

newfiltered_direct = arr[filter_arr_direct]

print("New filtered array (direct): ", newfiltered_direct)

print(filter_arr_direct)

New filtered array:  [44 45 46 47]
[False, False, False, True, True, True, True]
New filtered array (direct):  [43 44 45 46 47]
[False False  True  True  True  True  True]
