### Numpy practice 

In [1]:
import numpy as np

In [7]:
array1 = np.array([1,2,3,4])
print(array1)
print(array1.shape)

# This is two dimension array called matrix 
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)
print("Shape of array: ",array2.shape)
print("size of an array: ",array2.size)
print("datatype of array: ",array2.dtype)
print("dimesion: ",array2.ndim)
print(len(array2.shape) == array2.ndim)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
Shape of array:  (2, 4)
size of an array:  8
datatype of array:  int64
dimesion:  2
True


#### creating the basic array 

In [18]:
zeros = np.zeros((3,2))
print(zeros)

ones = np.ones((3,3))
print(ones)

empty = np.empty((2,2))
print(empty)

arange = np.arange(2,11,2)
print(arange)

#create an array with values that are spaced linearly in specified interva 
linespace = np.linspace(0,10, num=5)
print(linespace)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2.5  5. ]
 [ 7.5 10. ]]
[ 2  4  6  8 10]
[ 0.   2.5  5.   7.5 10. ]


### Adding, removing, and sorting elements 

In [ ]:
arr = np.array([1,4,12,2,0,9,11,7,5,13])
sorted1D = np.sort(arr)
print(arr)
print(sorted1D)

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

concatinate = np.concatenate((a,b))
print(concatinate)

x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[8,9,10,11]])
concat2D = np.concatenate((x,y), axis=0)
print(concat2D)

new_array = np.arange(0,11,2)
print(new_array)

print("\n")
reshape = np.reshape(new_array, shape=(2,3), order='C')
print(reshape)

flattern = reshape.flatten()
print(flattern)

# transpose the matrix into row into column and column into row
transpose = reshape.T
print(transpose)


[ 1  4 12  2  0  9 11  7  5 13]
[ 0  1  2  4  5  7  9 11 12 13]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10]


[[ 0  2  4]
 [ 6  8 10]]
[ 0  2  4  6  8 10]
[[ 0  6]
 [ 2  8]
 [ 4 10]]
