## Numpy ufunc 

In [1]:
import numpy as np

# wihout the numpy ufunc 
x = [1,2,3,4]
y = [5,6,7,8]
z = []

for i,j in zip(x,y):
    z.append(i+j)
print(z)

# now using the numpy ufunc 
sum = np.add(x,y)
print(sum)

[6, 8, 10, 12]
[ 6  8 10 12]


#### Creating own ufunc 

In [12]:
def myadd(x,y):
    return x+y

myaddvalue = np.frompyfunc(myadd,2,1)
print(myaddvalue([1,2,3,4],[5,6,7,8]))

print(type(myaddvalue))
print(type(np.sum))
print(type(np.concatenate))


[6 8 10 12]
<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>
<class 'numpy._ArrayFunctionDispatcher'>


#### ufunc simple artithmetic

In [13]:
arr1 = np.array([10,11,12,13])
arr2 = np.array([20,21,22,23])

newarr = np.add(arr1,arr2)
print(newarr)

subtraction = np.subtract(arr1,arr2)
print(subtraction)

multiplication = np.multiply(arr1,arr2)
print(multiplication)

division = np.divide(arr2,arr1)
print(division)

power = np.power(arr1,arr2)
print(power)

mod = np.mod(arr2,arr1)
print(mod)

remainder = np.remainder(arr1,arr2)
print(remainder)

# quotient and mod 
quotient = np.divmod(arr2,arr1)
print(quotient) # this will return the quotient and mod 


# for absolute values 
arr3 = np.array([-1,4,-7,3,11])
abs_value = np.absolute(arr3)

print(abs_value)

[30 32 34 36]
[-10 -10 -10 -10]
[200 231 264 299]
[2.         1.90909091 1.83333333 1.76923077]
[ 7766279631452241920  3105570700629903195  5729018530666381312
 -4649523274362944347]
[ 0 10 10 10]
[10 11 12 13]
(array([2, 1, 1, 1]), array([ 0, 10, 10, 10]))
[ 1  4  7  3 11]


### Rounding Decimals 

In [19]:
# Truncation means rounding the value 
import numpy as np 
array = np.trunc([-4.32232, 4.22327])
print(array)

# using the fix method 
array1 = np.fix([-3.1999, 3.6667])
print(array1)

# rounding to the nearest integer
array3 = np.around(3.1666, 2)
print(array3)

# floor
array4 = np.floor([3.6667, -3.1666])
print(array4)

# ceil
array5 = np.ceil([3.6667, -3.1666])
print(array5)

[-4.  4.]
[-3.  3.]
3.17
[ 3. -4.]
[ 4. -3.]


### Numpy LOGS

In [20]:
# NumPy provides functions to perform log at the base 2, e and 10.

# We will also explore how we can take log for any base by creating a custom ufunc.

# All of the log functions will place -inf or inf in the elements if the log can not be computed.

# Log at Base 2

import numpy as np

array6 = np.arange(1,10)
print(np.log2(array6))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


#### Log at Base 10

In [22]:
arr7 = np.arange(1,10)
print(np.log10(arr7))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [23]:
# Natural Log, or Log at Base e
arr8 = np.arange(1,10)
print(np.log(arr8))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### Log at any base 

In [24]:
from math import log
nplog = np.frompyfunc(log,2,1)
print(nplog(100,15))

1.7005483074552052


### Numpy Sumations

In [ ]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

newadd = np.add(arr_1, arr_2)
print(newadd)

newarr = np.sum([arr_1,arr_2]) ## this will give the total sum of the two array
print(newarr)

# summation over an axis 
rowaddition = np.sum([arr_1,arr_2], axis=1) # this will give the total by suming the row of an both array
print(rowaddition)

# summation over multiple axis
columnaddition = np.sum([arr_1,arr_2], axis=0) # This will give the total by suming the column of an both array
print(columnaddition)

# cummulative sum first term same second + first term for second term and so on
cumsum = np.cumsum([arr_2,arr_1], axis=0)
print(cumsum)

[5 7 9]
21
[ 6 15]
[5 7 9]
[[4 5 6]
 [5 7 9]]


### Numpy Products

In [ ]:
arr_product = np.array([1,2,3,4])

product = np.prod(arr_product)

print(product)

arr_product1 = np.array([1,2,3,4])
arr_product2 = np.array([5,6,7,8])

newProduct = np.prod([arr_product1,arr_product2])

print(newProduct)

# product over an axis

rowProduct = np.prod([arr_product1, arr_product2], axis=1)
print(rowProduct)

# cummulative product (it is like the factorial of the given numpy array)
arr_cumulative_product = np.cumprod(arr_product2)
print(arr_cumulative_product)


24
40320
[  24 1680]
[   5   30  210 1680]


### Differences 

In [47]:
arr_diff = np.array([1,6,2,9])

new_diff = np.diff(arr_diff)

print(new_diff)

# discrete difference of the array twice using the n=2
new_diff_with_n = np.diff(arr_diff, n=2)

print(new_diff_with_n)

[ 5 -4  7]
[-9 11]


### NumPy LCM Lowest Common Element

In [55]:
num1 = 4
num2 = 6

lcm = np.lcm(num1, num2)
print(lcm)

# numpy lcm with matrix 2d arrays is 
lcm_arr= np.array([3,6,9])
lcm_matrix = np.lcm.reduce(lcm_arr)
print(lcm_matrix)

# another example is 

ar_lcm = np.arange(1,10)
lcm_array = np.lcm.reduce(ar_lcm)
print(lcm_array)

12
18
2520


### NumPy GCD Greates Common Divisor

In [61]:
num3  = 6
num4 = 9

gcd = np.gcd(num3,num4)
print(gcd)

# numpy gcd with vector 1d arrays is
gcd_array = np.array([20,8,32,36,16])
gcd_of_whole_array = np.gcd.reduce(gcd_array)# here reduce is used to calculate the each element inside the vector 1d array

print(gcd_of_whole_array)

3
4


### NumPy Trigonometric Functions 

In [82]:
# trigonometric function
sin = np.sin(np.pi/3)
print(np.round(sin,2)) 

# finding the sine values in array 

sin_values = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
sin_array = np.sin(sin_values)
print(sin_array)


# cosine function
cos = np.cos(np.pi/3)
print(np.round(cos,2))

# Convert Degrees Into Radians 
angle_degrees = np.array([90,180,270,360])
convert_deg2rad = np.deg2rad(angle_degrees)
print(convert_deg2rad)

# Convert Radians to Degress 
angle_radians = np.array([np.pi/2,np.pi, 1.5*np.pi, 2*np.pi])
convert_rad2deg = np.rad2deg(angle_radians)
print(convert_rad2deg)

# Finding Angles arcsin(), arccos(), and arctan()
sin_angle = np.arcsin(1.0)
print(sin_angle)

# Angles of Each Value in Arrays 
values = np.array([1,-1,0.1])
angles = np.arcsin(values)
print(angles)

# Hypotenues : Finding hypotenues using pythagoras theorem in NumPy hypot()
base = 3
perp = 4

hypotenuse = np.hypot(base, perp)
print(hypotenuse)


0.87
[1.         0.8660254  0.70710678 0.58778525]
0.5
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]
5.0


### Hyperbolic Functions 

In [ ]:
import numpy as np

hyperbolic_sin = np.sinh(np.pi/3)
print(hyperbolic_sin) 


# Hyperbolic functions grow exponentially for larger values of x, while trigonometric functions oscillate between -1 and 1.
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5, np.pi/6])
values_cosh = np.cosh(arr)
print(values_cosh)

1.2493670505239751
[2.50917848 1.60028686 1.32460909 1.20397209 1.14023832]


#### Finding Angles 

In [4]:
arcsin = np.arcsinh(1.0)
print(arcsin)

0.881373587019543


### Angles of Each Value in Arrays 

In [5]:
values_list = np.array([0.1,0.2,0.5])
arctanh = np.arctanh(values_list)
print(arctanh)

[0.10033535 0.20273255 0.54930614]


### What is a Set? 
#### A set is a collection of unique objects, known as elements or members, that can be anything 

In [ ]:
import numpy as np 
# Create Sets in NumPy : unique() method to find unique elements
set1 = np.array([1,1,3,4,5,3,6,7,2,7,9,0,8,1])
unique_sets = np.unique(set1)
print(unique_sets) 

# Finding the union of two sets 
set2 = np.array([1,2,3,4])
set3 = np.array([3,4,5,6])
union_sets = np.union1d(set2, set3)
print(union_sets)

# Finding the intersection of two sets
set4 = np.array([1,2,3,4])
set5 = np.array([3,4,5,6])
intersection_sets = np.intersect1d(set4,set5, assume_unique=True) # assume_unique=True garyo vaney chai computation chai fast hunxa ra sets sanga deal garda always True garnu parxa 
print(intersection_sets)

# Finding Difference between two sets 
set6 = np.array([1,2,3,4])
set7 = np.array([3,4,5,6])
#set6 ra set7 match garxa ra set6 ma matra vako lai chai yesle dinxa 
difference_sets = np.setdiff1d(set6,set7, assume_unique=True)
print(difference_sets)

#Finding symmetric difference between two sets 
set8 = np.array([1,2,3,4])
set9 = np.array([3,4,5,6])
# Duita set bata unique value chai kun ho teslai chai herxa yesle chai 
symmetric_difference = np.setxor1d(set8, set9,assume_unique=True)
print(symmetric_difference)



[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
